/**
 * Action types
 */

export default {
    APP_SET_DATABASE_CLIENT: 'APP_SET_DATABASE_CLIENT',

    AUTH_LOGIN:    'AUTH_LOGIN',
    AUTH_SUCCESS:  'AUTH_SUCCESS',
    AUTH_ERROR:    'AUTH_ERROR',

    FORM_POPUP:    'FORM_POPUP',
    FORM_FILL:     'FORM_FILL',
    FORM_SUBMIT:   'FORM_SUBMIT',
    FORM_SUBMITED: 'FORM_SUBMITED',
    FORM_ERROR:    'FORM_ERROR',

    TASKS_FETCH:         'TASKS_FETCH',
    TASKS_FETCHED:       'TASKS_FETCHED',
    TASKS_ERROR:         'TASKS_ERROR',
    TASKS_CHANGE_OFFSET: 'TASKS_CHANGE_OFFSET',
    TASKS_CHANGE_ORDER:  'TASKS_CHANGE_ORDER',
};